import time
from selenium import webdriver
driver = webdriver.Chrome()
driver.maximize_window()
driver.implicitly_wait(7)
driver.get("https://practice.automationtesting.in/")
driver.execute_script("window.scrollBy(0, 600);")
Selenium_Ruby = driver.find_element_by_css_selector(".post-160 h3")
Selenium_Ruby.click()
time.sleep(5)
Reviews_tab = driver.find_element_by_css_selector(".reviews_tab")
Reviews_tab.click()
time.sleep(5)
Star = driver.find_element_by_css_selector(".star-5")
Star.click()
Review = driver.find_element_by_id("comment")
Review.send_keys("Nice Book!")
Name = driver.find_element_by_id("author")
Name.send_keys("Dima")
Email = driver.find_element_by_id("email")
Email.send_keys("test@gmail.ru")
time.sleep(5)
Submit = driver.find_element_by_id("submit")
Submit.click()
time.sleep(7)
driver.quit()